[package]
name = "tac_optimizer"
version = "0.1.0"
edition = "2018"
authors = [ "Chandrakana Nandi" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = { git = "ssh://git@github.com/oflatt/egg", rev = "df6635fc11a05c0229faea0fdabd3fc4fa237a63" }
etcommon-bigint = "0.2.10"
clap = { version = "3.0.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
log = "0.4"
env_logger = { version = "0.7", default-features = false }
once_cell = "1.8.0"
primitive-types = { version = "0.10", default-features = false, features = ["rlp"] }
rand = "0.8.4"
rust-evm = { git = "ssh://git@github.com/Certora/rust-evm", rev = "2ff524eac4e82a3678325d8d80f19af09423e5f4" }
symbolic_expressions = "5.0.3"
num = "0.3"
num-bigint = { version = "0.3", features = ["rand"] }
itertools = "0.10.3"
indexmap = "1.8.1"



[[bin]]
name = "tac_optimizer"
test = false
bench = false