[package]
name = "tac_optimizer"
version = "0.1.0"
edition = "2018"
authors = [ "Chandrakana Nandi" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tac_optimizer"
crate-type = ["cdylib"]

[dependencies]
jni = "0.8"
egg = "0.6.0"
etcommon-bigint = "0.2.10"
clap = "3.0.0-beta.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
log = "0.4"
env_logger = { version = "0.7", default-features = false }
once_cell = "1.8.0"
uniffi = "0.16.0"
evm-core = { path = "src/evm/core" }
primitive-types = { version = "0.10", default-features = false, features = ["rlp"] }
rand = "0.8.4"

[build-dependencies]
uniffi_build = {version = "0.14", features = [ "builtin-bindgen" ]}

