[package]
name = "tac_optimizer"
version = "0.1.0"
edition = "2018"
authors = [ "Chandrakana Nandi" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tac_optimizer"
crate-type = ["cdylib"]

[dependencies]
jni = "0.8"
egg = "0.7.1"
etcommon-bigint = "0.2.10"
clap = { version = "3.0.7", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
log = "0.4"
env_logger = { version = "0.7", default-features = false }
once_cell = "1.8.0"
uniffi = "0.16.0"
primitive-types = { version = "0.10", default-features = false, features = ["rlp"] }
rand = "0.8.4"
num = "0.3"
num-bigint = { version = "0.3", features = ["rand"] }

# This commit fixes the semantics of neg.
ruler = {path = "/Users/chandra/research/ruler-evm"}
#ruler = { git = "ssh://git@github.com/Certora/ruler-evm", rev = "ac20cdc2bdaafb0836a297ceaea2798365792424" }
#ruler = { git = "ssh://git@github.com/Certora/ruler-evm", rev = "816570cb57d2da3ed2c6e48416daa3149015083c" }

[build-dependencies]
uniffi_build = {version = "0.14", features = [ "builtin-bindgen" ]}

